// Code generated by Script. DO NOT EDIT.
// Source: script/codegen/main.go
//
// Generated by this command:
//
//	go run script/codegen/main.go

package zendesk

import (
	"context"
	"fmt"
	"github.com/JacobPotter/go-zendesk/internal/client"
)

func (z *Client) GetTicketCommentsIterator(ctx context.Context, opts *PaginationOptions) *Iterator[TicketComment] {
	return &Iterator[TicketComment]{
		CommonOptions: opts.CommonOptions,
		pageSize:      opts.PageSize,
		hasMore:       true,
		isCBP:         opts.IsCBP,
		pageAfter:     "",
		pageIndex:     1,
		ctx:           ctx,
		obpFunc:       z.GetTicketCommentsOBP,
		cbpFunc:       z.GetTicketCommentsCBP,
	}
}

func (z *Client) GetTicketCommentsOBP(ctx context.Context, opts *OBPOptions) ([]TicketComment, Page, error) {
	var data struct {
		TicketComments []TicketComment `json:"comments"`
		Page
	}

	tmp := opts
	if tmp == nil {
		tmp = &OBPOptions{}
	}

	path := fmt.Sprintf("/tickets/%d/comments.json", tmp.Id)
	u, err := client.AddOptions(path, tmp)

	if err != nil {
		return nil, Page{}, err
	}

	err = client.GetData(z, ctx, u, &data)
	if err != nil {
		return nil, Page{}, err
	}
	return data.TicketComments, data.Page, nil
}

func (z *Client) GetTicketCommentsCBP(ctx context.Context, opts *CBPOptions) ([]TicketComment, client.CursorPaginationMeta, error) {
	var data struct {
		TicketComments []TicketComment             `json:"comments"`
		Meta           client.CursorPaginationMeta `json:"meta"`
	}

	tmp := opts
	if tmp == nil {
		tmp = &CBPOptions{}
	}

	path := fmt.Sprintf("/tickets/%d/comments.json", tmp.Id)
	u, err := client.AddOptions(path, tmp)

	if err != nil {
		return nil, data.Meta, err
	}

	err = client.GetData(z, ctx, u, &data)
	if err != nil {
		return nil, data.Meta, err
	}
	return data.TicketComments, data.Meta, nil
}
