// Code generated by Script. DO NOT EDIT.
// Source: script/codegen/main.go
//
// Generated by this command:
//
//	go run script/codegen/main.go

package zendesk

import (
	"context"
	"github.com/JacobPotter/go-zendesk/internal/client"
)

func (z *Client) GetUsersIterator(ctx context.Context, opts *PaginationOptions) *Iterator[User] {
	return &Iterator[User]{
		CommonOptions: opts.CommonOptions,
		pageSize:      opts.PageSize,
		hasMore:       true,
		isCBP:         opts.IsCBP,
		pageAfter:     "",
		pageIndex:     1,
		ctx:           ctx,
		obpFunc:       z.GetUsersOBP,
		cbpFunc:       z.GetUsersCBP,
	}
}

func (z *Client) GetUsersOBP(ctx context.Context, opts *OBPOptions) ([]User, Page, error) {
	var data struct {
		Users []User `json:"users"`
		Page
	}

	tmp := opts
	if tmp == nil {
		tmp = &OBPOptions{}
	}

	u, err := client.AddOptions("/users.json", tmp)

	if err != nil {
		return nil, Page{}, err
	}

	err = client.GetData(z, ctx, u, &data)
	if err != nil {
		return nil, Page{}, err
	}
	return data.Users, data.Page, nil
}

func (z *Client) GetUsersCBP(ctx context.Context, opts *CBPOptions) ([]User, client.CursorPaginationMeta, error) {
	var data struct {
		Users []User                      `json:"users"`
		Meta  client.CursorPaginationMeta `json:"meta"`
	}

	tmp := opts
	if tmp == nil {
		tmp = &CBPOptions{}
	}

	u, err := client.AddOptions("/users.json", tmp)

	if err != nil {
		return nil, data.Meta, err
	}

	err = client.GetData(z, ctx, u, &data)
	if err != nil {
		return nil, data.Meta, err
	}
	return data.Users, data.Meta, nil
}
