# Terraform Provider release workflow.
name: Versioning

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    branches:
      - master

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - name: Git Semantic Version
        id: semantic
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          major_pattern: "feat(major):"
          minor_pattern: "feat:"
          bump_each_commit: true
          bump_each_commit_patch_pattern: "fix:"
          enable_prerelease_mode: true
          branch: master
          tag_prefix: "v"
          debug: true
      - name: Create Release
        if: ${{ steps.semantic.outputs.version != steps.semantic.outputs.previous_version }}
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semantic.outputs.version_tag }}
          release_name: ${{ steps.semantic.outputs.version_tag }}
          draft: false
          prerelease: false
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
      - name: Publish
        if: ${{ steps.semantic.outputs.version != steps.semantic.outputs.previous_version }}
        run: GOPROXY=proxy.golang.org go list -m github.com/JacobPotter/go-zendesk@${{ steps.semantic.outputs.version_tag }}
